### ISSUE TITLE
Set-up Kanban board project

### ISSUE THREAD

**Issue by ryxtor** [yersel500/space-travelers-hub#25]
## Hello! 👋🏻 

[Here is the link to the Kanban board project.](https://github.com/yersel500/space-travelers-hub/projects/1)
[Here is the link to the repository.](https://github.com/yersel500/space-travelers-hub)

We are a group of two people.

**Comment by Amrhub** [comment]
# Approved 💯 ✅ 🥳 🎈 🎉 

Hi Team, 👋🏻 

Your project is complete!  There is nothing else to say.
Congratulations! 🎉 

![](https://media.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif)
